language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t surbhirvt/docker-react -f Dockerfile.dev .

script:
  # - docker run surbhirvt/docker-react npm run test -- --coverage
  - docker run -e CI=true surbhirvt/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-306942347119"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY"