language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t surbhirvt/docker-react -f Dockerfile.dev .

script:
  # - docker run surbhirvt/docker-react npm run test -- --coverage
  - docker run -e CI=true surbhirvt/docker-react npm run test